### ISSUE TITLE
Issue I would like to solve

### ISSUE THREAD

**Issue by galabl** [mzusin/toolcool-range-slider#10]
Hi,

I have one slider with two pointers of which one is disabled and the other is not.

I also have the overlap option set to true as you can see in codepen demo.

What doesn't work for me is that when I click with mouse on the disabled pointer, or on the value that's greater that the value of the disabled pointer, the not disabled pointer doesn't go to that value.

Any advise on how to achieve this?

Codepen: https://codepen.io/dyxtbwsr-the-vuer/pen/GRXaVRQ

**Comment by mzusin** [comment]
Hi,
The issue should be fixed now.
Please use the latest version of the script and let me know if all is well:
https://cdn.jsdelivr.net/npm/toolcool-range-slider@4.0.24/dist/toolcool-range-slider.min.js

**Comment by galabl** [comment]
Thank you @mzusin it works now

**Comment by mzusin** [comment]
You're welcome.
