### ISSUE TITLE
onMouseUp event bug

### ISSUE THREAD

**Issue by galabl** [mzusin/toolcool-range-slider#11]
Codepen: https://codepen.io/galabl/pen/qBKgLEG

Since onchange event is fired too often it's not really reliable for me to use it(it fires even if the value didn't change) I wanted to use the onMouseUp event but it doesn't fire every time.

For example, if you click and drag slider pointer, it can happen that the mouse pointer is not on top of the slider pointer sometimes, in that case, the mouse up event is not fired.

Could you please take a look at this.

Thanks.

**Comment by mzusin** [comment]
The 'onchange' event should be fixed now in v4.0.25, It should only fire when value changes:

You can use it it with CDN:
https://cdn.jsdelivr.net/npm/toolcool-range-slider@4.0.25/dist/toolcool-range-slider.min.js

Codepen example:
https://codepen.io/mzusin/pen/qBJbYap
