### ISSUE TITLE
Any way of fixing the styling for mark labels

### ISSUE THREAD

**Issue by kremenovic** [mzusin/toolcool-range-slider#12]
Is there any way we can break mark labels or fix the latest one to be full-width like the first one? 

![Screenshot_2](https://user-images.githubusercontent.com/35824199/234260691-3a558d45-e3ef-4d4f-96e5-c2602867a2bb.jpg)

**Comment by mzusin** [comment]
Please share your code or in https://codepen.io/ or https://jsbin.com/ so I could check it.

**Comment by mzusin** [comment]
Closing because there was no further response.

**Comment by kremenovic** [comment]
Hi,

Sorry for my late response. Here's the code: https://jsbin.com/puqefudopo/edit?html,output

**Comment by mzusin** [comment]
There are 2 ways to add custom CSS to the slider:
- https://toolcool-range-slider.mzsoft.org/pages/add-css-api.html
- https://toolcool-range-slider.mzsoft.org/pages/css-links.html

The example below breaks all labels:
https://jsbin.com/begarak/edit?html,js,output


```js
 const $slider = document.getElementById('slider');

 $slider.addCSS(`
    .mark-value{
        max-width: 60px;
        text-align: center;
    }
  `);
```
