### ISSUE TITLE
range bug: unable to move value1 pointer once it's been positioned to value2 pointer

### ISSUE THREAD

**Issue by timbowhite** [mzusin/toolcool-range-slider#15]
Thank you for this great slider! I will be using it on tld-list.com and some other projects.

Bug:
When you have a range (i.e. value1 and value2), and you slide the value1 pointer to the same position of the value2 pointer, the value1 pointer cannot be moved again. If the value2 pointer is in the max right hand position, both pointers become locked.

Reproduce:
1. Go here: https://jsfiddle.net/7ok4atrj/
2. Slide the left pointer (value1) all the way over to the right, on top of the value2 pointer. Release mouse button.
3. Attempt to move value1 pointer.

Firefox 102.0.1 and Chrome 114

**Comment by mzusin** [comment]
Thank you for the feedback. The issue should be fixed in v4.0.28
https://jsfiddle.net/rosehip/p1f7qtm9/1/
