### ISSUE TITLE
moving-tooltip-plugin: allow custom value formatting function

### ISSUE THREAD

**Issue by timbowhite** [mzusin/toolcool-range-slider#16]
It'd be nice to be able to supply a custom function to format tooltip values, especially for values like currency where the values need to be dynamically formatted with commas and decimal points (i.e. $500.00 and $5,000.00 and $10k).

Currently this cannot not be achieved with ```tooltipUnits``` and ```tooltipUnitType```.

**Comment by mzusin** [comment]
I added **formatTooltipValue** function to the plugin settings. The function accepts a value from the slider and should return the formatted string.
  
You can find the live example here:
https://jsfiddle.net/rosehip/yu4dse6h/6/

Or code sample below:

```html
<tc-range-slider
       id="custom-format-func-slider"

       min="10000"
       max="20000"
       step="0.01"
       round="1"

       value1="13000"
       value2="15000"
       value3="17000"

       moving-tooltip="true"
       moving-tooltip-distance-to-pointer="40"
       moving-tooltip-width="70"
       moving-tooltip-height="30"
       moving-tooltip-bg="#721d82"
       moving-tooltip-text-color="#efefef"
       moving-tooltip-units="$"
       moving-tooltip-units-type="prefix"

       slider-bg="#CBD5E1"
       slider-bg-hover="#94A3B8"
       slider-bg-fill="#475569"
       slider-width="100%"></tc-range-slider>
</div>

<script src="https://cdn.jsdelivr.net/npm/toolcool-range-slider@4.0.28/dist/plugins/tcrs-moving-tooltip.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/toolcool-range-slider@4.0.28/dist/toolcool-range-slider.min.js "></script>
<script>
      const $customFormatSlider = document.getElementById('custom-format-func-slider');
      $customFormatSlider.formatTooltipValue = (value) => {
        return Number(value).toLocaleString('en-US', { minimumFractionDigits: 2 });
      };
</script>
```

The updated documentation is here:
https://toolcool-range-slider.mzsoft.org/pages/moving-tooltip-plugin.html

**Comment by timbowhite** [comment]
This is great, thank you!

**Comment by mzusin** [comment]
If it works for you, could you please close the issue?
