### ISSUE TITLE
How to use the library in Next?

### ISSUE THREAD

**Issue by Nickk4** [mzusin/toolcool-range-slider#17]
I've installed the library: `yarn add toolcool-range-slider`.
But how can I now use it in a Next project?

On a page I tried:

    import 'toolcool-range-slider';

And inside a render:

    <tc-range-slider min={0} max={30} value={subscription} />

But this returns the error: "Property 'min' does not exist on type 'DetailedHTMLProps<HTMLAttributes<RangeSlider>, RangeSlider>'.ts(2322)"

**Comment by mzusin** [comment]
The library uses web components under the hood, and it seems that next has some issue with it: https://github.com/vercel/next.js/issues/11619

The possible workaround I've found so far is to use the script tag as follows:
https://nextjs.org/docs/messages/no-script-tags-in-head-component

```tsx
import Script from 'next/script';

export default function Home() {

  return (
    <main className="flex min-h-screen flex-col items-center justify-between p-24 bg-white">
      <Script src="https://cdn.jsdelivr.net/npm/toolcool-range-slider/dist/toolcool-range-slider.min.js" />
      <div>
        <tc-range-slider min={ 0 } max={ 30 } value={ 0 } />
      </div>
    </main>
  )
}

```
