### ISSUE TITLE
Moving tooltip question 

### ISSUE THREAD

**Issue by ghost** [mzusin/toolcool-range-slider#18]
I've got a slider with three pointers and I want to show the tooltips with pointers 1 and 3 below the line and pointer 2 above the line. If you compare the pointers in these two when you play the tune:

https://irish.session.nz/tunes-archive/abbey-leix/

https://dev.session.nz/tunes-archive/abbey-leix/

Love the package!

**Comment by mzusin** [comment]
You can try using custom CSS with this API:
https://toolcool-range-slider.mzsoft.org/pages/add-css-api.html

The CSS could be:
```css
.pointer-1{
   transform: translateY(50%);
}
```
