### ISSUE TITLE
non-passive event listener to a scroll-blocking 'touchmove' event

### ISSUE THREAD

**Issue by jubbs** [mzusin/toolcool-range-slider#21]
[Violation] Added non-passive event listener to a scroll-blocking 'touchmove' event. Consider marking event handler as 'passive' to make the page more responsive. 

Got this error in chrome. Changed the following lines in javascript made it go away and seemed to fix the issue. Not sure where this is in your source sorry.

```
                        i.addEventListener("touchmove", z),
                        i.addEventListener("touchstart", z),

>>>>

                        i.addEventListener("touchmove", z, {
                                passive: !1,
                            }),
                        i.addEventListener("touchstart", z),
                        F ||
                            document.addEventListener("wheel", Q, {
                                passive: !1,
                            }),
```

**Comment by mzusin** [comment]
Hi,
Do you see this warning in the documentation site, for example here?
https://toolcool-range-slider.mzsoft.org/pages/basic-usage.html

If yes, what chrome version do you use?
I can't reproduce this issue.
